sudo: false
dist: trusty
language: java
  
install: mvn install -DskipTests=true -Dgpg.skip=true

jdk:
  - openjdk9
  - oraclejdk9
  - openjdk10
  - openjdk11

notifications:
  email: false

# whitelist
branches:
  only:
    - master