sudo: false
dist: trusty
language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  
install: mvn install -DskipTests=true -Dgpg.skip=true

jdk:
  - openjdk9
  - openjdk10
  - openjdk11
  
matrix:
  include:
# 9
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
    - env: JDK='OpenJDK 9'
      install: . ./install-jdk.sh -F 9
# 10
    - env: JDK='Oracle JDK 10'
      jdk: oraclejdk10
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
# 11
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL

notifications:
  email: false

# whitelist
branches:
  only:
    - master